[project]
name = "t8spectrum"
version = "0.1.0"
description = ""
authors = [{ name = "Daniel Castaño Rodríguez", email = "UO288241@uniovi.es" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["python-dotenv (>=1.0.1,<2.0.0)"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.9"
pytest = "^8.3.5"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
]
ignore = []
